### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by pixar2390** [pixar2390/chat-space#10]
# IPアドレス
54.248.206.3

何卒よろしくお願いします。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

### [修正箇所]
**①「Create Account」「Login」「Adit Account」の文字色をカリキュラムの指定通りにしましょう
②Sendボタンを2回押して、アラートが出現した後で、リロードしなくてもメッセージが送信できるようにしましょう
③送信したメッセージ同士の間隔をカリキュラムの指定通りにしましょう**

### [修正箇所の現在の画像]
**①**
<img width="273" alt="スクリーンショット 2020-06-03 12 18 29" src="https://user-images.githubusercontent.com/49669977/83938496-af76dd80-a80f-11ea-9162-0b123a533efc.png">

**③**
<img width="783" alt="スクリーンショット 2020-06-06 16 05 56" src="https://user-images.githubusercontent.com/49669977/83938507-c289ad80-a80f-11ea-8307-69ccc1b0602c.png">


修正が完了次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by pixar2390** [comment]
レビューいただきありがとうございます。
①modulesフォルダの中のgroup.scss内にh２要素全てのプロパティを指定するコマンドがかいてあったため修正しました。

②deferred.always()を用いて非同期通信に成功・失敗した両方の場合でも送信ボタンが押せなくなる機能をオフにしました。

③マージンとパテディングで当たっているプロパティは違いますが、要素構成が少し代わりますので私はマージンを使用し40px間隔を開けております。見本も同様に40px だけ間隔があると思うのですが、何が間違っているのか教えていただけますか？

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

>③マージンとパテディングで当たっているプロパティは違いますが、要素構成が少し代わりますので私はマージンを使用し40px間隔を開けております。

こちら、再度確認したところ問題ありませんでした！

※今後実装に関する質問がありましたら、メンターに確認をお願いします！
